spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minmao?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 08240030xzh.
    type: com.alibaba.druid.pool.DruidDataSource
