server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minmao?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 08240030xzh.
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password: 08240030xzh.
  jackson:
    generator:
      write-numbers-as-strings: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl